from .usuarioView import UsuarioListView, UsuarioRetrieveUpdateDeleteView
from .medicoView import MedicoListCreateView, MedicoRetrieveUpdateView
from .familiarView import FamiliarListCreateView, FamiliarRetrieveUpdateView
from .enfermeroView import EnfermeroListCreateView, EnfermeroRetrieveUpdateView
from .pacienteView import PacienteListCreateView, PacienteRetrieveUpdateView  