# Generated by Django 4.1.1 on 2022-09-23 21:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rol', models.CharField(max_length=20, verbose_name='Rol')),
                ('nombres', models.CharField(max_length=50, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('genero', models.CharField(max_length=20, verbose_name='Genero')),
                ('celular', models.CharField(max_length=50, verbose_name='Celular')),
                ('direccion', models.CharField(max_length=50, verbose_name='Direccion')),
                ('ciudad', models.CharField(max_length=50, verbose_name='Ciudad')),
                ('fechaNacimiento', models.DateField()),
                ('latitud', models.CharField(max_length=50, verbose_name='Latitud')),
                ('longitud', models.CharField(max_length=50, verbose_name='Longitud')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='Username')),
                ('password', models.CharField(max_length=256, verbose_name='Password')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Enfermero',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('area', models.CharField(max_length=50, verbose_name='Area')),
                ('auxiliar', models.BooleanField(default=False, verbose_name='Auxiliar')),
                ('usuarioEnfermero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enfermero', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('usuarioFamiliar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='familiar', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('oximetria', models.FloatField(default=0, verbose_name='Oximetria')),
                ('fCardiaca', models.FloatField(default=0, verbose_name='FCardiaca')),
                ('fRespiratoria', models.FloatField(default=0, verbose_name='FRespiratoria')),
                ('temperatura', models.FloatField(default=0, verbose_name='Temperatura')),
                ('presionArterial', models.FloatField(default=0, verbose_name='PresionArterial')),
                ('glicemias', models.FloatField(default=0, verbose_name='Glicemias')),
                ('diagnostico', models.CharField(max_length=256, verbose_name='Diagnostico')),
                ('sugerencia', models.CharField(max_length=256, verbose_name='Sugerencia')),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('especialidad', models.CharField(max_length=50, verbose_name='Especialidad')),
                ('registro', models.IntegerField(default=0, verbose_name='Registro')),
                ('usuarioMedico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medico', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('historiaClinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paciente', to='homeCareApp.historiaclinica')),
                ('usuarioEnfermero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paciente', to='homeCareApp.enfermero')),
                ('usuarioFamiliar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paciente', to='homeCareApp.familiar')),
                ('usuarioMedico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paciente', to='homeCareApp.medico')),
                ('usuarioPaciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paciente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
