# Generated by Django 4.1.1 on 2022-10-03 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeCareApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiaclinica',
            name='usuarioPaciente',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='historiaClinica', to=settings.AUTH_USER_MODEL),
        ),
    ]
